
		ctf = {
			"sc1":[
				{
					"title":"C2 Domain",
					"body":"Identify the domain in which the server is constantly communicates with.",
					"pts":"100",
					"flag":"smell-like-teen-armpits-sweat.tk",
					"hint":[],
				},
				{
					"title":"Listening Port",
					"body":"What is the port used by attacker in the listener backdoor",
					"pts":"200",
					"flag":"443",
					"hint":[],
				},
				{
					"title":"Leaked DB",
					"body":"Which database was leaked during the incident?",
					"pts":"100",
					"flag":"employees",
					"hint":[],
				},
				{
					"title":"New Account",
					"body":"What is the new account created by the attacker in the compromised server?",
					"pts":"100",
					"flag":"r00t",
					"hint":[],
				},
				{
					"title":"Malicious Process",
					"body":'"Identify all malicious processes exist within the compromised server. <br>Submit answer in format of process1,process2,process3,processX (sort by alphabetical order A-Z)"',
					"pts":"200",
					"flag":"kprocess,stch",
					"hint":[],
				},
				{
					"title":"Beacon",
					"body":"Calculate the shortest time gap (round to nearest second) between each successful beacons response, from C2 domain to compromised server.",
					"pts":"200",
					"flag":"",
					"hint":[],
				},
				{
					"title":"Payload Type",
					"body":"What type of payload used in the backdoor found within the compromised server?",
					"pts":"300",
					"flag":"",
					"hint":[],
				},
				{
					"title":"Bad Guy Tool",
					"body":"Find out the password of the downloaded archive file used by the attacker.",
					"pts":"300",
					"flag":"",
					"hint":[],
				},
				{
					"title":"Attacker IP Address",
					"body":"Attacker has connected to the planted backdoor. What is the IP address used by the attacker during the connection?",
					"pts":"200",
					"flag":"65.60.10.132",
					"hint":[],
				},
			],
			"sc2":[
				{
					"title":"The 2nd Account",
					"body":"Identify if there is another Windows account",
					"pts":"100",
					"flag":"pentadbir",
					"hint":[],
				},
				{
					"title":"Command &amp; Control",
					"body":'"Identify the IP address and port number of the C2 used by the attacker. <br>Submit answer in the format of ipaddress:portnumber"',
					"pts":"200",
					"flag":"",
					"hint":[],
				},
				{
					"title":"The name is, Bot",
					"body":'"Identify the bot user name &amp; the application used to communicate.<br>Submit answer in format of username,appname in small cap"',
					"pts":"400",
					"flag":"",
					"hint":[],
				},
				{
					"title":"Threat Actor",
					"body":"Who is behind this malicious activity?",
					"pts":"100",
					"flag":"",
					"hint":[],
				},
				{
					"title":"Remote",
					"body":'"Attacker has been accessing the victim machine. Provide the service the attacker used &amp; from which IP address.<br>Submit answer in format of servicename,ipaddress"',
					"pts":"200",
					"flag":"rdp,161.142.8.233",
					"hint":["tcp 3389"],
				},
				{
					"title":"Binary Path",
					"body":"Identify full path of the malware process<br>(Answer in small cap letters)",
					"pts":"100",
					"flag":"",
					"hint":[],
				},
				{
					"title":"Wher Its Coming",
					"body":"Identify the domain where source of infection was dropped..",
					"pts":"200",
					"flag":"",
					"hint":[],
				},
				{
					"title":"The Log",
					"body":"Identify full path of the logged file(Answer in small cap)",
					"pts":"200",
					"flag":"",
					"hint":[],
				},
				{
					"title":"Hash",
					"body":"Identify the hash of the binary file.",
					"pts":"100",
					"flag":"",
					"hint":[],
				},
				{
					"title":"Get The Password",
					"body":"What is the attacker's next target?<br>Through OSINT, our Threat Intel team found a copy of the file highlights the threat actor 's next target. We are now sharing the file here, but it's password protected.",
					"pts":"400",
					"flag":"",
					"hint":[],
				},
				{
					"title":"Stay Persistance",
					"body":"The malware has modified some files to stay persistent. How?<br><br><br>Answer in the following format:<br>1. &lt;registry full path&gt;=&lt;registry key name&gt;<br>2. Answer in small cap.<br>",
					"pts":"300",
					"flag":"",
					"hint":[],
				},
				{
					"title":"Type of exploit",
					"body":"Find the exploit identifier for the initial infection vector.",
					"pts":"400",
					"flag":"",
					"hint":[],
				},
			]
		}